-- 마스터 인명 테이블 추가 (PM/영업담당 등)
CREATE TABLE IF NOT EXISTS contacts_master (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    role VARCHAR(20) NOT NULL CHECK (role IN ('pm','sales')),
    phone VARCHAR(30),
    active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_contacts_master_role ON contacts_master(role);
CREATE INDEX IF NOT EXISTS idx_contacts_master_name ON contacts_master(name);

ALTER TABLE contacts_master ENABLE ROW LEVEL SECURITY;

-- RLS 정책: 읽기는 인증 사용자 모두 허용, 쓰기는 관리자만 (애플리케이션 레벨에서 체크)
-- Supabase에서는 정책을 SQL로 더 정교하게 줄 수도 있으나, 여기서는 앱에서 user_role 검사로 제어합니다.


